services:
  api:
    build:
      dockerfile: Dockerfile
    image: local/tboyd-eb/librechat-local
    volumes:
      - ./librechat.yml:/app/librechat.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock